# Generated by Django 4.2.9 on 2024-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload',
            field=models.FileField(null=True, upload_to='swaggerfiles/'),
        ),
    ]
