# Generated by Django 4.2.9 on 2024-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swagger',
            name='upload',
            field=models.FileField(upload_to='swaggerfiles/'),
        ),
    ]
